name: booking-order-app # change this to your app name
services:
  field-service: # change this to your service name
    container_name: field-service # change this to your service name
    # image: maulanairfanf/field-service:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8001' # change this to your port
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network
    driver: bridge
